include:
  - project: TankerHQ/gitlab-ci-files
    ref: f4fbb073851e9944d07179f3234d9c6035a98ade
    # TODO replace with react-native.yml later on
    file: /ios.yml

##########
# Stages #
##########

stages:
  - check

########
# Jobs #
########

default:
  before_script:
    # TODO: should be done by the include script above I think
    - poetry install

check/ios/deployed:
  stage: check
  extends:
    - .tags/macos
    - .rules/mr/auto
  script:
    - yarn --cwd example react-native run-ios --verbose

check/android/deployed:
  stage: check
  extends:
    - .tags/linux
    - .rules/mr/auto
  script:
    - sudo chgrp 1000 -f /dev/kvm
    - poetry run python run-ci.py build-and-test
  image: registry.gitlab.com/tankerhq/docker/sdk-react-native:latest

check/ios/downstream:
  stage: check
  extends:
    - .tags/macos
    - .before-script/download-artifacts
    - .rules/check/downstream/ios
  script:
    - yarn --cwd example react-native run-ios --verbose
