include:
  - project: TankerHQ/gitlab-ci-files
    ref: 2023-12-12-275
    file: /common.yml

variables:
  SDK_NATIVE_CONAN_REFERENCE: tanker/latest-stable@
  GIT_DEPTH: 1

############
# Workflow #
############

workflow:
  rules:
    # web pipelines for releases only
    - if: $CI_PIPELINE_SOURCE == "web" && $SDK_REACT_NATIVE_RELEASE_VERSION !~ /\A\d+\.\d+\.\d+(-(alpha|beta)\d+)?\z/
      when: never
    # we must specify version of sdk-ios/sdk-android to avoid clients upgrading them by accident
    - if: $CI_PIPELINE_SOURCE == "web" && $SDK_ANDROID_RELEASE_VERSION !~ /\A\d+\.\d+\.\d+(-(alpha|beta)-\d+)?\z/
      when: never
    - if: $CI_PIPELINE_SOURCE == "web" && $SDK_IOS_RELEASE_VERSION !~ /\A\d+\.\d+\.\d+(-(alpha|beta)\d+)?\z/
      when: never
    - if: !reference [.if-invalid-native-conan-reference, if]
      when: never
    - if: '$CI_MERGE_REQUEST_TITLE =~ /.*\[preview].*/'
      variables:
        CONAN_REMOTE: "artifactory-preview"
    - when: always
      variables:
        CONAN_REMOTE: "artifactory"


###########
# Default #
###########

default:
  before_script:
    - poetry run python -m pip install --upgrade pip
    - poetry install
  image: registry.gitlab.com/tankerhq/docker/sdk-react-native:latest

.before-script/download-artifacts:
  before_script:
    - !reference [default, before_script]
    - poetry run python run-ci.py download-artifacts --project-id=$UPSTREAM_PROJECT_ID --pipeline-id=$UPSTREAM_PIPELINE_ID --job-name=$UPSTREAM_JOB_NAME
    - poetry run python run-ci.py reset-branch $(cat branch_name.txt)
    - poetry run python -m pip install --upgrade pip
    - poetry install

.artifacts:
  artifacts:
    when: always
    paths:
      - logcat.txt
      - screenshot.png

##########
# Stages #
##########

stages:
  - lint
  - check

########
# Jobs #
########

lint:
  stage: lint
  rules:
    - !reference [.rules/mr/auto, rules]
    - !reference [.rules/web/auto, rules]
    - !reference [.rules/push-master-or-feat, rules]
  script:
    - poetry run python run-ci.py lint
  tags: !reference [.tags/linux, tags]

.detox/android:
  stage: check
  needs: []
  extends:
    - .artifacts
  before_script:
    - !reference [default, before_script]
    - sudo chgrp 1000 -f /dev/kvm
  tags: !reference [.tags/compilation-linux, tags]

detox/android/from-sources:
  extends:
    - .detox/android
    - .rules/mr/manual
  script:
    - poetry run python run-ci.py prepare android --isolate-conan-user-home --remote $CONAN_REMOTE --use-tanker=deployed --tanker-ref=$SDK_NATIVE_LATEST_CONAN_REFERENCE
    - poetry run python run-ci.py detox android --os-version $OS_VERSION --react-native-arch $RN_ARCH
  parallel:
        matrix:
          - OS_VERSION: ["oldest", "latest"]
            RN_ARCH: ["old", "new"]

detox/android/all-from-sources:
  extends:
    - .detox/android
    - .rules/native-from-sources
  script:
    - poetry run python run-ci.py prepare android --isolate-conan-user-home --remote $CONAN_REMOTE --use-tanker=same-as-branch
    - poetry run python run-ci.py detox android --os-version $OS_VERSION --react-native-arch $RN_ARCH
  parallel:
        matrix:
          - OS_VERSION: ["oldest", "latest"]
            RN_ARCH: ["old", "new"]

detox/android/deployed:
  extends:
    - .detox/android
  rules:
    - !reference [.rules/web/auto, rules]
    - !reference [.rules/mr/manual, rules]
  script:
    - poetry run python run-ci.py detox android --os-version $OS_VERSION --react-native-arch $RN_ARCH
  parallel:
      matrix:
        - OS_VERSION: ["oldest", "latest"]
          RN_ARCH: ["old", "new"]

detox/android/downstream:
  extends:
    - .detox/android
    - .rules/check/downstream/android
  before_script:
    - !reference [.before-script/download-artifacts, before_script]
    - !reference [.detox/android, before_script]
  script:
    - poetry run python run-ci.py detox android

.detox/ios:
  stage: check
  needs: []
  extends:
    - .artifacts

detox/ios/from-sources:
  extends:
    - .detox/ios
    - .rules/mr/manual
  script:
    - poetry run python run-ci.py prepare ios --isolate-conan-user-home --remote $CONAN_REMOTE --use-tanker=deployed --tanker-ref=$SDK_NATIVE_LATEST_CONAN_REFERENCE
    - poetry run python run-ci.py detox ios --react-native-arch $RN_ARCH
  parallel:
    matrix:
      - RN_ARCH: ["old", "new"]
        CPU_ARCH: ["arm", "x86_64"]
  tags:
    - macos
    - $CPU_ARCH

detox/ios/all-from-sources:
  extends:
    - .detox/ios
    - .rules/mr/manual
  script:
    - poetry run python run-ci.py prepare ios --isolate-conan-user-home --remote $CONAN_REMOTE --use-tanker=same-as-branch
    - poetry run python run-ci.py detox ios --react-native-arch $RN_ARCH
  parallel:
    matrix:
      - RN_ARCH: ["old", "new"]
        CPU_ARCH: ["arm", "x86_64"]
  tags:
    - macos
    - $CPU_ARCH

detox/ios/deployed:
  extends:
    - .detox/ios
  rules:
    - !reference [.rules/web/auto, rules]
    - !reference [.rules/mr/manual, rules]
  script:
    - poetry run python run-ci.py detox ios --react-native-arch $RN_ARCH
  parallel:
    matrix:
      - RN_ARCH: ["old", "new"]
        CPU_ARCH: ["arm", "x86_64"]
  tags:
    - macos
    - $CPU_ARCH

detox/ios/downstream/arm:
  extends:
    - .detox/ios
    - .rules/check/downstream/ios/arm
    - .before-script/download-artifacts
  script:
    - poetry run python run-ci.py detox ios --react-native-arch $RN_ARCH
  parallel:
    matrix:
      - RN_ARCH: ["old"]
  tags: !reference [.tags/macos/arm, tags]

detox/ios/downstream/x86_64:
  extends:
    - .detox/ios
    - .rules/check/downstream/ios/x86_64
    - .before-script/download-artifacts
  script:
    - poetry run python run-ci.py detox ios --react-native-arch $RN_ARCH
  parallel:
    matrix:
      - RN_ARCH: ["old"]
  tags: !reference [.tags/macos/x86_64, tags]
