include:
  - project: TankerHQ/gitlab-ci-files
    ref: 2e85be62c4fe0d2291bc3a9ff153cd8e3edffaaf
    file: /react-native.yml

##########
# Stages #
##########

stages:
  - check

########
# Jobs #
########

default:
  before_script:
    - poetry install

check/ios/deployed:
  stage: check
  extends:
    - .tags/macos
    - .rules/mr/manual
  script:
    - poetry run python run-ci.py build-and-test ios

check/android/deployed:
  stage: check
  extends:
    - .tags/linux
    - .rules/mr/manual
  script:
    - sudo chgrp 1000 -f /dev/kvm
    - poetry run python run-ci.py build-and-test android
  image: registry.gitlab.com/tankerhq/docker/sdk-react-native:latest

check/android/downstream:
  stage: check
  extends:
    - .tags/linux
    - .before-script/download-artifacts
    - .rules/check/downstream/android
  script:
    - sudo chgrp 1000 -f /dev/kvm
    - poetry run python run-ci.py build-and-test android
  image: registry.gitlab.com/tankerhq/docker/sdk-react-native:latest

check/android/from-sources:
  stage: check
  extends:
    - .tags/linux
    - .rules/mr/manual
  script:
    - sudo chgrp 1000 -f /dev/kvm
    - poetry run python run-ci.py prepare android --use-tanker=deployed --tanker-ref=$SDK_NATIVE_LATEST_CONAN_REFERENCE
    - poetry run python run-ci.py build-and-test android
  image: registry.gitlab.com/tankerhq/docker/sdk-react-native:latest

check/android/all-from-sources:
  stage: check
  extends:
    - .tags/linux
    - .rules/mr/manual
  script:
    - sudo chgrp 1000 -f /dev/kvm
    - poetry run python run-ci.py prepare android --use-tanker=same-as-branch
    - poetry run python run-ci.py build-and-test android
  image: registry.gitlab.com/tankerhq/docker/sdk-react-native:latest

check/ios/downstream:
  stage: check
  extends:
    - .tags/macos
    - .before-script/download-artifacts
    - .rules/check/downstream/ios
  script:
    - poetry run python run-ci.py build-and-test ios

check/ios/from-sources:
  stage: check
  extends:
    - .tags/macos
    - .rules/mr/manual
  script:
    - poetry run python run-ci.py prepare ios --use-tanker=deployed --tanker-ref=$SDK_NATIVE_LATEST_CONAN_REFERENCE
    - poetry run python run-ci.py build-and-test ios

check/ios/all-from-sources:
  stage: check
  extends:
    - .tags/macos
    - .rules/mr/manual
  script:
    - poetry run python run-ci.py prepare ios --use-tanker=same-as-branch
    - poetry run python run-ci.py build-and-test ios
