require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

source 'https://cdn.cocoapods.org/'
source 'https://github.com/TankerHQ/PodSpecs.git'

platform :ios, '10.0'

target 'ClientReactNativeExample' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'tanker-client-react-native', :path => '../..'
  if File.exist?("../../pod/Tanker.podspec")
    pod 'Tanker', :path => "../../pod"
    pod 'RNFS', :path => '../node_modules/react-native-fs'

  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
    end
  end
end
