package com.tanker.clientreactnative

import com.facebook.react.bridge.ReactApplicationContext

abstract class ClientReactNativeSpec internal constructor(context: ReactApplicationContext) :
    NativeClientReactNativeSpec(context) {
    // This is meant to be empty!
    // For the new architecture this is generated by React-Native from the Typescript spec.
}
